algorithm_kwargs:
  batch_size: 4
  eval_freq: 1
  num_epochs: 512
  start_epoch: 0
amp: false
dataset_kwargs:
  batch_size: 4
  crop_size: 512
  data_root: ./Meddata
  dataset: medical
  db_name: all
  image_size: 512
  normalization: vit
  num_workers: 12
  split: train
inference_kwargs:
  im_size: 512
  window_size: 512
  window_stride: 256
log_dir: seg_base_p16_384
net_kwargs:
  backbone: vit_base_patch16_384
  d_model: 768
  decoder:
    drop_path_rate: 0.0
    dropout: 0.1
    n_cls: 2
    n_layers: 2
    name: mask_transformer
  distilled: false
  drop_path_rate: 0.1
  dropout: 0.0
  image_size: !!python/tuple
  - 512
  - 512
  n_cls: 2
  n_heads: 12
  n_layers: 12
  normalization: vit
  painter_depth: 4
  patch_size: 16
optimizer_kwargs:
  clip_grad: null
  epochs: 512
  iter_max: 3934720
  iter_warmup: 0.0
  lr: 0.001
  min_lr: 1.0e-06
  momentum: 0.9
  opt: sgd
  poly_power: 0.9
  poly_step_size: 1
  sched: polynomial
  weight_decay: 0.0
resume: true
version: normal
world_batch_size: 4
